/** Acceptance of browser feedback: icon, single tooltip and airport-specific KPIs. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const url=process.argv[2],out=path.resolve(process.argv[3]);if(!/^http:\/\/(127\.0\.0\.1|localhost):\d+\/$/.test(url||''))throw Error('Local URL required');
let browser;const results=[],errors=[];const pass=(name,detail='')=>{results.push({name,status:'passed',detail});console.log('PASS',name,detail)};
(async()=>{await fs.mkdir(out,{recursive:true});browser=await chromium.launch({channel:'chrome',headless:false,args:['--window-position=-32000,-32000']});const p=await browser.newPage({viewport:{width:1600,height:1000}});p.on('pageerror',e=>errors.push(e.message));
await p.route('**/js/app.js*',async route=>{const response=await route.fetch();await route.fulfill({response,body:`(()=>{window.qaMaps={};const factory=L.map;L.map=function(id,options){const map=factory(id,options);window.qaMaps[id]=map;return map;};})();\n`+await response.text()});});
const settle=async key=>p.waitForFunction(key=>document.getElementById('tab-'+key)?.getAttribute('aria-busy')==='false',key,{timeout:60000});
const tab=async key=>{await p.locator(`#mainNav [data-tab="tab-${key}"]`).click();await settle(key)};
const shot=async name=>p.screenshot({path:path.join(out,name+'.jpg'),type:'jpeg',quality:85});
await p.goto(url,{waitUntil:'networkidle'});await settle('overview');await shot('01-symbol-im-diagramm');
await p.locator('#btnAiModal').click();await p.locator('#aiExamplesToggle').click();const questions=await p.locator('[data-ai-question]').allTextContents();assert.equal(questions.length,5);assert.ok(questions.every(q=>q.endsWith('?')));assert.ok(questions.every(q=>!q.includes('Verwaltungsvorlage')));assert.equal(await p.locator('#aiExamples > p').evaluate(n=>getComputedStyle(n).textTransform),'none');assert.doesNotMatch(await p.locator('#aiExamples > p').innerText(),/Geplante/);await shot('02-ki-fragen');await p.keyboard.press('Escape');pass('Five actual questions, readable introduction');
for(const key of ['overview','road','rail','iww','intermodal','maritime','airfreight','forecast','toll']){
 await tab(key);
 if(key==='toll'){if(!await p.locator('#tollMunicipalitySearchInput').isVisible())await p.locator('#btnToggleAnalysisPanel').click();await p.waitForFunction(()=>!document.getElementById('selectTollMonth').disabled);await p.locator('#tollMunicipalitySearchInput').fill('Duisburg');await p.locator('#tollMunicipalityAutocompleteList .autocomplete-item').filter({hasText:'Duisburg'}).first().click();await settle('toll');}
 const buttons=p.locator('.tab-pane.active .btn-chart-enlarge');
 for(let i=0;i<await buttons.count();i++){
  const button=buttons.nth(i);if(!await button.isEnabled())continue;
  assert.equal(await button.getAttribute('aria-label'),'Diagramm vergrößern');assert.equal(await button.getAttribute('title'),null);assert.equal((await button.textContent()).trim(),'');
  assert.ok(await button.evaluate(n=>{const a=n.getBoundingClientRect(),b=n.closest('.card-header').getBoundingClientRect();return a.top>=b.top&&a.bottom<=b.bottom&&a.right<=b.right&&a.width<=28}));await button.hover();assert.equal(await p.locator('#chartExpandHint').evaluate(n=>getComputedStyle(n).backgroundColor),'rgb(255, 255, 255)');
  await button.click();await p.locator('#modalChartLarge.active').waitFor();
  const target=await p.evaluate(()=>{const c=Chart.getChart('largeChartCanvas');const ds=c.data.datasets.findIndex(d=>d.data.some(v=>Number(v)!==0));const idx=c.data.datasets[ds].data.findIndex(v=>Number(v)!==0);const q=c.getDatasetMeta(ds).data[idx].getCenterPoint();const r=c.canvas.getBoundingClientRect();return {x:r.left+q.x*r.width/c.width,y:r.top+q.y*r.height/c.height}});
  await p.mouse.move(target.x,target.y);await p.waitForTimeout(500);
  const tooltip=await p.evaluate(()=>{const c=Chart.getChart('largeChartCanvas');return {opacity:c.tooltip.opacity,external:c.options.plugins.tooltip.external,enabled:c.options.plugins.tooltip.enabled,caret:c.options.plugins.tooltip.caretSize}});assert.ok(tooltip.opacity>0&&tooltip.enabled&&tooltip.caret>0,JSON.stringify(tooltip));assert.equal(tooltip.external,null);assert.equal(await p.locator('.chart-hover-tooltip.is-visible').count(),0);
  if(key==='overview'&&i===1)await shot('03-eine-sprechblase');await p.keyboard.press('Escape');
 }
 pass('Header icon and single native tooltip: '+key);
}
await tab('airfreight');if(!await p.locator('#selectAirfreightAirport').isVisible())await p.locator('#btnToggleAnalysisPanel').click();await p.locator('#selectYear').selectOption('2024');await p.locator('#selectAirfreightAirport').selectOption('EDDP');
assert.match(await p.locator('#airfreightNationalTitle').innerText(),/Leipzig\/Halle/i);assert.match(await p.locator('#airfreightNationalValue').innerText(),/1,38 Mio\. t/);assert.match(await p.locator('#airfreightYoYValue').innerText(),/-0,6/);assert.match(await p.locator('#airfreightAirportCount').innerText(),/28,9 %/);assert.equal(await p.locator('#airfreightTop3Share').innerText(),'2 von 22');await shot('04-leipzig-kennzahlen');pass('Leipzig airport amount, YoY, share of airport sum, rank');
await p.locator('#selectDirection').selectOption('outbound');assert.match(await p.locator('#airfreightNationalValue').innerText(),/714,8 Tsd\. t/);await p.locator('#selectDirection').selectOption('inbound');assert.match(await p.locator('#airfreightNationalValue').innerText(),/668,5 Tsd\. t/);await p.locator('#selectDirection').selectOption('balance');assert.match(await p.locator('#airfreightNationalValue').innerText(),/46,3 Tsd\. t/);assert.match(await p.locator('#airfreightAirportCountTitle').innerText(),/absoluten/i);assert.match(await p.locator('#airfreightTop3Title').innerText(),/absolutem Saldo/i);pass('Airport directional and balance KPIs use corresponding scope');
await p.locator('#selectDirection').selectOption('all');await p.locator('#selectAirfreightMetric').selectOption('flights');assert.match(await p.locator('#airfreightNationalValue').innerText(),/49\.948/);await p.locator('#selectYear').selectOption('2025');assert.equal(await p.locator('#selectAirfreightAirport').inputValue(),'EDDP');assert.equal(await p.locator('#airfreightNationalValue').innerText(),'48.657 Flüge');assert.match(await p.locator('#airfreightYoYValue').innerText(),/-2,6/);assert.doesNotMatch(await p.locator('#airfreightNationalSub').innerText(),/nicht belastbar/);pass('Reviewed 2025 airport flights retain selection and show corrected values');
await p.locator('#selectYear').selectOption('2024');await p.locator('#selectAirfreightMetric').selectOption('tonnes');await p.locator('#selectAirfreightAirport').selectOption('');assert.match(await p.locator('#airfreightNationalTitle').innerText(),/Deutschland/i);assert.match(await p.locator('#airfreightNationalValue').innerText(),/4,69 Mio\. t/);assert.equal(await p.locator('#airfreightAirportCount').innerText(),'22');assert.match(await p.locator('#airfreightTop3Title').innerText(),/Top 3/i);
await p.waitForTimeout(300);const airportPoint=await p.evaluate(()=>{const map=qaMaps.airfreightLeafletMap;const q=map.latLngToContainerPoint([51.420657,12.232705]),r=map.getContainer().getBoundingClientRect();return{x:r.left+q.x,y:r.top+q.y}});await p.mouse.click(airportPoint.x,airportPoint.y);assert.equal(await p.locator('#selectAirfreightAirport').inputValue(),'EDDP');assert.match(await p.locator('#airfreightNationalTitle').innerText(),/Leipzig\/Halle/i);pass('Map click updates KPIs, clearing restores national scope');
await p.setViewportSize({width:1366,height:768});await shot('05-laptop');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.setViewportSize({width:390,height:844});assert.equal(await p.locator('.tab-pane.active .btn-chart-enlarge').first().isHidden(),true);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.locator('#btnAiModal').click();await p.locator('#modalAi.active').waitFor();if(await p.locator('#aiExamples').getAttribute('hidden')!==null)await p.locator('#aiExamplesToggle').click();await p.locator('[data-ai-question]').last().scrollIntoViewIfNeeded();await shot('06-mobile-fragen');await p.locator('[data-ai-question]').last().click();assert.match(await p.locator('#aiQuestionInput').inputValue(),/Wo wächst das Schienengüteraufkommen laut Prognose von 2019 bis 2040 am stärksten\?/);pass('Laptop and mobile layout, all five mobile questions usable');assert.deepEqual(errors,[]);await fs.writeFile(path.join(out,'feedback-results.json'),JSON.stringify({results,errors},null,2));
})().catch(async e=>{console.error(e);await fs.mkdir(out,{recursive:true});await fs.writeFile(path.join(out,'feedback-failure.json'),JSON.stringify({error:e.stack,results,errors},null,2));process.exitCode=1}).finally(async()=>browser?.close());
